---
title: "HomeWork2"
author: "Harikrishna"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
cran_mirror <- "https://cran.rstudio.com/"
options(repos = c(CRAN = cran_mirror))
install.packages("tidyr")
```

### Problem 1
```{r echo=TRUE}
set.seed(210)
install.packages("ggplot2")
library(ggplot2)
rejection_sampling <- function(n) {
  samples <- numeric(n)
  c <- 2.5
  
  for (i in 1:n) {
    repeat {
      y <- rcauchy(1)
      acceptance_prob <- dnorm(y) / (c * dcauchy(y))
      if (runif(1) < acceptance_prob) {
        samples[i] <- y
        break
      }
    }
  }
  return(samples)
}
sample_size <- 10000
sample <- rejection_sampling(sample_size)
sample_percentiles <- quantile(sample, seq(0, 1, 0.01))
standard_normal_percentiles <- qnorm(seq(0, 1, 0.01))

qq_plot <- ggplot() +
  geom_point(aes(sample_percentiles, standard_normal_percentiles), color = "blue") +
  geom_abline(intercept = 0, slope = 1, linetype = "dashed", color = "red") +
  labs(title = "Q-Q Plot", x = "Sample Percentiles", y = "Standard Normal Percentiles")

# Display Q-Q plot
print(qq_plot)
```


### Problem 2

```{r echo=TRUE}
# Set the seed
set.seed(210)
library(ggplot2)
rejection_sampling <- function(n) {
  samples <- numeric(n)
  c <- 2.5
  for (i in 1:n) {
    repeat {
      y <- rcauchy(1)
      acceptance_prob <- dnorm(y) / (c * dcauchy(y))
      if (runif(1) < acceptance_prob) {
        samples[i] <- y
        break
      }
    }
  }
  return(samples)
}

sample_size <- 10000
sample <- rejection_sampling(sample_size)
sample_percentiles <- quantile(sample, seq(0, 1, 0.01))
standard_normal_percentiles <- qnorm(seq(0, 1, 0.01))

qq_plot <- ggplot() +
  geom_point(aes(sample_percentiles, standard_normal_percentiles), color = "blue") +
  geom_abline(intercept = 0, slope = 1, linetype = "dashed", color = "red") +
  labs(title = "Q-Q Plot", x = "Sample Percentiles", y = "Standard Normal Percentiles")

print(qq_plot)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
